repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    # -   id: check-added-large-files
    #     exclude: ddcuimap/semantic_search/resources/dict_umls_upsert_ids.pkl
    -   id: debug-statements

#-   repo: https://github.com/PyCQA/flake8
#    rev: 6.0.0
#    hooks:
#    -   id: flake8

#-   repo: https://github.com/timothycrosley/isort
#    rev: 5.11.3
#    hooks:
#    -   id: isort
