import os
from dotenv import load_dotenv
import subprocess
from typing import Dict, List, Literal
from pydantic import Field, PrivateAttr
from pathlib import Path

from agency_swarm.tools import BaseTool
from agency_swarm import Agent, Agency, set_openai_key
from agency_swarm import Agency
from agency_swarm.tools import Retrieval, CodeInterpreter

from instructor import OpenAISchema

from JobProposalGents.instructions import (
    ceo_instructions,
    analyst_instructions,
    writer_instructions,
    editor_instructions,
    dev_instructions,
)
from tools import (
    ExecutePyFile,
    File,
    ExtractJobDetails,
    GenerateProposal,
)


# Define Agent Roles

ceo = Agent(
    name="CEO",
    description="Responsible for facilitating smooth and efficient communication between the user and specialized agents.",
    instructions=ceo_instructions,  # can be a file like ./instructions.md
    files_folder=None,
    tools=[File],
)


dev = Agent(
    name="DEV",
    description="Responsible for creating and/or executing Python scripts to fulfill the user's request.",
    instructions=dev_instructions,
    files_folder=None,
    tools=[ExecutePyFile, File],
)

analyst = Agent(
    name="ANALYST",
    description="Responsible for analyzing job postings and extracting essential job details and retrieving user's relevant qualifications.",
    instructions=analyst_instructions,
    files_folder="JobProposalGents\\user_files",
    tools=[ExtractJobDetails, Retrieval],
)

writer = Agent(
    name="WRITER",
    description="Responsible for generating job proposals based on the given prompt.",
    instructions=writer_instructions,
    files_folder="JobProposalGents\\user_files",
    tools=[GenerateProposal, Retrieval],
)

editor = Agent(
    name="EDITOR",
    description="Responsible for editing the job proposal generated by the WRITER.",
    instructions=editor_instructions,
    files_folder="JobProposalGents\\user_files",
    tools=[Retrieval],
)

# 4. Define Agency Communication Flows
# get current path
fp_shared_instructions = os.getcwd() + "JobProposalGents\\manifesto.md"

# get current path string from path

agency = Agency(
    [
        ceo,
        [ceo, analyst],
        [ceo, writer],
        [writer, editor],
        [editor, writer],
        [editor, ceo],
    ],
    shared_instructions=fp_shared_instructions,
)  # shared instructions for all agents

# 5. Run Demo
agency.demo_gradio(height=900)
